version: '3.9'

services:

  shop-serv-app:
    build:
      dockerfile: ./Dockerfile
    container_name: shopserv
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - shop-db
  shop-db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop_service
      - POSTGRES_USER=dakz
      - POSTGRES_PASSWORD=123321

